name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install:ci
      - name: Checking types
        run: yarn check-types
      - name: Linting *.ts/*.tsx files
        run: yarn lint-ts
        if: always()
      - name: Linting *.scss files
        run: yarn lint-scss
        if: always()
      - name: Unit testing
        run: yarn test-unit
        if: always()

  storybook:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install:ci
      - name: Building storybook
        run: yarn storybook:build
      - name: UI testing
        run: yarn test-ui:ci
