name: linting, testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        id: install
        run: yarn install:ci
      - name: Checking types
        run: yarn check-types
        if: steps.install.conclusion == 'success'
      - name: Linting *.ts/*.tsx files
        run: yarn lint-ts
        if: steps.install.conclusion == 'success'
      - name: Linting *.scss files
        run: yarn lint-scss
        if: steps.install.conclusion == 'success'

  testing:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install:ci
      - name: Unit testing
        run: yarn test-unit
      - name: Move unit test report
        run: mv reports/unit .github-reports
      - name: Building storybook
        id: build
        run: yarn storybook:build
      - name: UI testing
        id: ui
        run: yarn test-ui:ci
      - name: Generate HTML report
        id: ui_report
        run: yarn test-ui:report-only
        if: always()
      - name: Move ui test report
        run: mv .loki .github-reports
        if: always()
      - name: Setup Pages
        uses: actions/configure-pages@v2
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.github-reports'
        if: always()
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        if: always()
